# Generated by Django 2.0.5 on 2018-07-19 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(null=True, upload_to='imageusers', verbose_name='Изображение')),
                ('story_false', models.BooleanField(default=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='is_following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='is_followers', to=settings.AUTH_USER_MODEL)),
                ('story', models.ManyToManyField(blank=True, related_name='story', to='videoblog.VideoBlog')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('view_later', models.ManyToManyField(blank=True, related_name='view_latter', to='videoblog.VideoBlog')),
            ],
        ),
    ]
