# Generated by Django 2.0.5 on 2018-07-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoblog', '0004_auto_20180724_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipadress',
            name='ip_adress',
            field=models.GenericIPAddressField(default='192.168.0.1'),
        ),
    ]
